apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-assignment-deployment
  labels:
    app: nagp-assignment-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagp-assignment-devops
  template:
    metadata:
      labels:
        app: nagp-assignment-devops
    spec:
      containers:
      - name: nagp-assignment-devops
        image: dtr.nagarro.com:443/hello-kube-ajay 
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: nagp-assignment-service
  labels:
    run: nagp-assignment-deployment
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 80
    nodePort: 30007
  selector:
    run: nagp-assignment-devops