apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-assignment-deployment
  labels:
    app: nagp-assignment-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagp-assignment-devops
  template:
    metadata:
      labels:
        app: nagp-assignment-devops
    spec:
      containers:
      - name: nagp-assignment-devops
        image: dtr.nagarro.com:443/hello-kube-ajay 
        ports:
        - containerPort: 8089